// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type Post struct {
	ID        *string `json:"id"`
	CreatedAt *string `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt"`
	Title     *string `json:"title"`
	Published *bool   `json:"published"`
	Desc      *string `json:"desc"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
